### ISSUE TITLE
Build in Linux alarm 3.10.18-18-ARCH armv7l GNU/Linux DOESN WORK !!!

### ISSUE THREAD

**Issue by aperfeito** [libretro-mirrors/reicast-emulator#48]
I always stop here : Doesn't matter the configuration look the flags: Feet like a clove in my processor Tegra TK1:

HAVE_NEON = 1
TARGET_NAME   := reicast
NO_REC=1

ASMFLAGS   := -marm -mcpu=cortex-a15.cortex-a7 -mfloat-abi=hardFLAGS  := -mfloat-abi=hard
LDFLAGS  :=
INCFLAGS :=
LIBS     :=
CFLAGS   := -DARM_HARDFP -mfloat-abi=hard
CXXFLAGS :=
CC_AS ?= $(AS)
CPUFLAGS += -DHOST_CPU=arm -DNO_ASM -DARM -D__arm__ -DARM_ASM -DNOSSE -mfloat-abi=hard D__NEON_OPT -mfpu=neon
_________________________________________________________________________________________

Always stop here I tried change in the common.cpp  HOST_CPU=  CPU_ARM or CPU_GENERIC and crashes in the same way

core/libretro/common.cpp:254:2: error: #error Unsupported HOST_CPU
 #error Unsupported HOST_CPU
  ^~~~~
core/libretro/common.cpp:340:2: error: #error JIT: Not supported arch
 #error JIT: Not supported arch

Reicast may fix this BUG
